config/routes.rb
Rails.application.routes.draw do
  get 'addFavorite' => "favorites#create"
  get 'removeFavorite' => "favorites#destroy"
  get 'favorites' => "favorites#index"
  get 'login' => "sessions#new"
  get "logout" => "sessions#destroy"
  get "signup" => "users#new"
  get "auth/:provider/callback" => "authentications#create"
  resources :users, except: [:index, :new]
  resources :sessions, except: [:index, :new, :update, :show, :new, :destroy]
  resources :recipes do 
      resources :comments, except: [:index]
      resources :favorites, only: [:index,:create, :destroy]
  end
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "sites#about" #call about method from sites route
  # Defines the root path route ("/")
   root "sites#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_rich_text :content
    belongs_to :recipe
    belongs_to :user
    validates :content, presence: true
    validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 10}
    #validates :user_id, numericality: { greater_than: 0}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate
  before_action :load_recipe
  before_action :load_comment, except: [:new, :index, :create]
  def index
  end
  def new
    @comment = Comment.new
  end
  def create
    @comment = Comment.new comment_params #the params are created from new's form
    @comment.user = current_user
    if @recipe.comments << @comment #successfully created and added
      redirect_to recipe_comment_path(@recipe,@comment), notice: "Comment Created" #recipe_comment_path(@recipe,@comment)
    else
      #calling new -> new form
      render :new, status: :unprocessable_entity
    end
  end
  def show
    
  end

  def edit
    if unauthorized
      redirect_to recipe_comment_path(@recipe,@comment), alert: "Invalid Request"
    end
  end
  
  def update
    if unauthorized
      redirect_to recipe_comment_path(@recipe,@comment), alert: "Invalid Request"
    else 
      if @comment.update comment_params
        redirect_to recipe_comment_path(@recipe,@comment), notice: "Comment Updated"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end 
  def destroy
    if unauthorized
      redirect_to recipe_comment_path(@recipe,@comment), alert: "Invalid Request"
    else
      @comment.destroy
      #render :index this wouldn't work since you need to pass it recipe to load :)
      redirect_to @recipe, alert: "Comment deleted" #recipe_comments_path(@recipe)
    end
  end
  private
  def unauthorized
    current_user != @comment.user
  end
  def comment_params
    params.require(:comment).permit(:content, :user_id,:rating)
  end 
  def load_comment
    @comment = @recipe.comments.find params[:id] #only find within comments belong to specific recipe
  end
  def load_recipe
    @recipe = Recipe.find params[:recipe_id] # the params receive from an action, referring to recipe_id
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment)%>" class="comment">
        <%local_time = comment.updated_at.in_time_zone('Hawaii')
        formatted_time = local_time.strftime("%m/%d/%y %I:%M%P")
        %>
        <% title2 =  " : " + formatted_time %>
        <% if comment.user%>
          <% title2 = comment.user.name + title2 %>
        <% else %>
          <% title2 = "null" + title2 %>
        <% end %>
        <h4> <%= link_to_unless_current title2, recipe_comment_path(@recipe,comment)%></h4>
        <p><%= comment.content%></p>
        <p>Rating: <%= comment.rating%>/10</p>
</div>

app/views/comments/_form.html.erb
<%= bootstrap_form_with(model: [@recipe,@comment]) do |f| %>
  <%= f.alert_message "Please fix the erros below.", error_summary: false %> <!-- f: we don't need it to display task.errors -->
  <%= f.rich_text_area :content %>
  <%= f.number_field :rating %>
  <%= f.primary @comment.persisted? ? 'Update Comment' : "Make Comment" %>
<% end %>

app/views/comments/edit.html.erb
<%title "Edit comment"%>
<%= render 'form'%>

app/views/comments/index.html.erb
<% title "Comments for "+@recipe.name %>

<%= render @recipe.comments%>

<p>
    <%= link_to "Comment", new_recipe_comment_path(@recipe), class: "btn btn-primary" %>
    <%= link_to "Back to recipe", @recipe%>
</p>

app/views/comments/new.html.erb
<% title "New Comment"%>
<%= render 'form'%>

app/views/comments/show.html.erb
<%= title "Comment for "+@recipe.name%>
<%= render @comment%>
<div class="dropdown">
  <% if current_user == @comment.user %>
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Options
  </button> | 
  <% end %>
  <%= link_to "Back to comments", @recipe %> <!-- recipe_comments_path(@recipe) -->

  <ul class="dropdown-menu">
    <li><%= link_to "Edit Comment", edit_recipe_comment_path(@recipe,@comment), class: "dropdown-item" %> </li>
    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Delete Comment</a></li>
  </ul>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Warning</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure to delete this recipe?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to 'Yes', [@recipe,@comment], method: :delete, class: 'btn btn-danger' %>  
      </div>
    </div>
  </div>
</div>