config/routes.rb
Rails.application.routes.draw do
  get 'addFavorite' => "favorites#create"
  get 'removeFavorite' => "favorites#destroy"
  get 'favorites' => "favorites#index"
  get 'login' => "sessions#new"
  get "logout" => "sessions#destroy"
  get "signup" => "users#new"
  get "auth/:provider/callback" => "authentications#create"
  resources :users, except: [:index, :new]
  resources :sessions, except: [:index, :new, :update, :show, :new, :destroy]
  resources :recipes do 
      resources :comments, except: [:index]
      resources :favorites, only: [:index,:create, :destroy]
  end
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "sites#about" #call about method from sites route
  # Defines the root path route ("/")
   root "sites#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_one_attached :image
    has_many :favorites, dependent: :destroy
    has_many :fans, through: :favorites, source: :user
    has_many :comments, :dependent => :destroy
    belongs_to :user
    validates :name, presence: true
    validates :budget, presence: true
    validates :ingredients, presence: true
    validates :cookingDirection, presence: true
    validates :storesAvailable, presence: true
    validates :servingSize, numericality: { greater_than: 0 }
    validates :prepTime, comparison: { greater_than: 0 }
    validates :cookTime, comparison: { greater_than: 0 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate
  before_action :load_recipe, except: [:new, :index, :create] #before action is for before calling any method
  #HTTP: GET
  #Path: /recipes
  def index 
    @recipes = Recipe.all
  end
  #HTTP: GET
  #PATH: /recipes/new
  def new
    @recipe = Recipe.new
  end
  #HTTP: POST
  #PATH: /recipes
  def create
    @recipe = Recipe.new recipe_params
    @recipe.user = current_user #create by current user
    if @recipe.save
      redirect_to recipes_path, notice: "Recipe created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  #HTTP: GET
  #PATH: /recipes/:id
  #This method get called by the routes then it pass params to html views or get params from previous post views.
  def show
   
  end
  #HTTP: GET
  #PATH: /recipes/:id/edit
  def edit
    if unauthorized
      redirect_to recipes_path, alert: "Invalid Request"
    end
  end
  #HTTP: DELETE
  #PATH: /recipes/:id
  def destroy
    if unauthorized
      redirect_to @recipe, alert: "Invalid Request"
    else
      @recipe.destroy
      redirect_to recipes_path, alert: "Recipe ' #{@recipe.name} ' was deleted."
    end
  end
  #HTTP: PATCH/PUT
  #PATH: /recipes/:id
  def update
    if unauthorized
      redirect_to @recipe, alert: "Invalid Request"
    else 
      if @recipe.update recipe_params
        redirect_to @recipe, notice: "Recipe was updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end
  
  private
  def unauthorized
    current_user != @recipe.user
  end
  def load_recipe
    @recipe = Recipe.find params[:id] # is this param from the view? query? -> controller -> another view?
  end
  def recipe_params
    params.require(:recipe).permit(:name,:imgUrl,:servingSize,:budget,:prepTime,:cookTime,:ingredients,:storesAvailable,:cookingDirection, :image)
  end  
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= bootstrap_form_with(model: @recipe) do |f| %>
  <%= f.alert_message "Please fix the erros below.", error_summary: false %> <!-- f: we don't need it to display task.errors -->
  <%= f.text_field :imgUrl %>
  <%= f.file_field :image, label: "Recipe Image" %>
  <%= f.text_field :name %>
  <%= f.number_field :servingSize %>
  <%= f.number_field :budget %>
  <%= f.number_field :prepTime %>
  <%= f.number_field :cookTime %>
  <%= f.text_field :ingredients %>
  <%= f.text_field :storesAvailable %>
  <%= f.text_field :cookingDirection %>
  <%= f.primary @recipe.persisted? ? 'Update Recipe' : "Create Recipe" %>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="card" style="width: 18rem;">
  <img src="<%= recipe.image.attached? ? url_for(recipe.image) : recipe.imgUrl %>" class="card-img-top" alt="<%= recipe.name %>'s image">
  <div class="card-body">
    <h5 class="card-title"> <%= link_to_unless_current recipe.name, recipe %></h5>
    <h6>Contributed by : <%= link_to recipe.user.name, user_path(recipe.user)%></h6>
    <% if current_user.favorited_recipes.include?(recipe) %>
      <% favorite = current_user.favorites.find_by(recipe: recipe) %>
      <%= button_to 'Unmark Favorite', recipe_favorite_path(recipe, favorite), method: :delete, class: 'bi bi-bookmark-star btn btn-danger' %>
    <% else %>
     <%= button_to 'Mark Favorite', recipe_favorites_path(recipe), method: :post, class: 'bi bi-bookmark-star btn btn-warning' %>
    <% end %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><p><strong>Serving:</strong> <%= recipe.servingSize %></p></li>
    <li class="list-group-item"<p><strong>Budget:</strong> <%= recipe.budget %></p></li>
    <li class="list-group-item"<p><strong>Prep time:</strong> <%= recipe.prepTime %></p></li>
    <li class="list-group-item"<p><strong>Cook time:</strong> <%= recipe.cookTime %></p></li>
    <li class="list-group-item"<p><strong>Ingredients:</strong> <%= recipe.ingredients %></p></li>
    <li class="list-group-item"<p><strong>Direction:</strong> <%= recipe.cookingDirection %></p></li>
  </ul>
</div>

<br>

app/views/recipes/edit.html.erb
<% title "Edit Recipe"%>

<%= render 'form' %>

app/views/recipes/index.html.erb
<% title "Recipes" %>
<p>
    <%= link_to "New Recipe", new_recipe_path, class: "btn btn-primary" %>
    
</p>
<div class="recipe-row">

    <% @recipes.each do |recipe| %>
        <div class="recipe-col m-2 align-self-stretch">
            <%= render  recipe %> <%#partial: "recipe2", locals: {recipe: recipe}%> 
        </div>
    <% end %>
</div>

app/views/recipes/new.html.erb
<% title "Create Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<% title "View Recipe" %>
<div id="recipe_comments" class = "recipe-row"> 
  <div class = "recipe-col"> 
    <%= render @recipe %> <!-- you need the instance variable here, recipe in index is loop var -->
    
    <!--
    <%= link_to "Edit Recipe", edit_recipe_path %> 
    <%= button_to 'Delete Recipe', @recipe, method: :delete, class: 'btn btn-danger', form: { data: {turbo_confirm: "Are you sure?"}} %>-->
    <div class="dropdown">
      <% if current_user == @recipe.user %>
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Options
        </button> | 
      <% end %>
      
      
      <%= link_to "All Recipes", recipes_path %>
    
      <ul class="dropdown-menu">
         <!--<li><%= link_to "Comments", recipe_comments_path(@recipe), class: "dropdown-item" %> </li>-->
         <li><%= link_to "Edit Recipe", edit_recipe_path, class: "dropdown-item" %> </li>
        <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Delete</a></li>
      </ul>
    </div>
  </div>
  <div class = "recipe-col">
    <h3>Comments</h3>
    <%= render @recipe.comments%>
    <%= link_to "Comment", new_recipe_comment_path(@recipe), class: "btn btn-primary" %>
  </div>
      

</div>




<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Warning</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure to delete this recipe?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to 'Yes', @recipe, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>