config/routes.rb
Rails.application.routes.draw do
  get 'addFavorite' => "favorites#create"
  get 'removeFavorite' => "favorites#destroy"
  get 'favorites' => "favorites#index"
  get 'login' => "sessions#new"
  get "logout" => "sessions#destroy"
  get "signup" => "users#new"
  get "auth/:provider/callback" => "authentications#create"
  resources :users, except: [:index, :new]
  resources :sessions, except: [:index, :new, :update, :show, :new, :destroy]
  resources :recipes do 
      resources :comments, except: [:index]
      resources :favorites, only: [:index,:create, :destroy]
  end
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about" => "sites#about" #call about method from sites route
  # Defines the root path route ("/")
   root "sites#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :comments
    has_many :favorites, dependent: :destroy
    has_many :favorited_recipes, through: :favorites, source: :recipe
    has_one_attached :avatar
    has_secure_password
    validates :name, presence: :true
    validates :title, presence: :true
    validates :email, format: { with: /@/, message: "Must have an @"}, uniqueness: true
    
    def self.new_from_hash(user_hash) #sefl is static
        user = User.new user_hash
        user.password_digest = 0
        user
    end
    
    def has_password?
        self.password_digest.nil? || self.password_digest != '0'
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate, except: [:new, :create]
  before_action :load_user, except: [:new, :create] #before action is for before calling any method
  def new
    if session[:user_hash]
      @user = User.new_from_hash session[:user_hash]
      @user.valid?
    else
      @user = User.new
    end
  end
  def create
    if session[:user_hash]
      @user = User.new_from_hash session[:user_hash]
      @user.name = user_params[:name]
      @user.email = user_params[:email]
      @user.title = user_params[:title]
      @user.role = user_params[:role]
    else
      @user = User.new user_params
    end
    if @user.save
      login(@user)
      session[:user_hash] = nil
      redirect_to root_path, notice: "You are successfully sign up."
    else
      render :new, status: :unprocessable_entity
    end
  end
  def show
  end
  def edit
    if unauthorized
      redirect_to user_path(@user), alert: "You are not authorized to edit"
    end
  end
  def update
    if unauthorized
      redirect_to user_path(@user), alert: "You are not authorized to edit"
    else
      update_params = user_password_params
      if not @user.has_password?
         update_params = user_password_params.except(:password,:password_confirmation,:password_challenge)
      end
      if @user.update update_params
        redirect_to @user, notice: "You have successfully updated your info"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end
  def destroy
    if unauthorized
      redirect_to root_path, alert: "Invalid Request"
    else
      @user.destroy
      logout
      redirect_to login_path, alert: "User: ' #{@user.name} ' was deleted."
    end
  end 
  private
  def unauthorized
    current_user != @user
  end
  def user_params
   params.require(:user).permit(:name,:email,:password,:password_confirmation,:title,:role,:avatar)
  end
  def user_password_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:password_challenge,:title,:role,:avatar).with_defaults(password_challenge: '')
  end
  def load_user
    @user = User.find params[:id]
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= bootstrap_form_with(model: @user) do |f| %>
  <%= f.alert_message "Please fix the erros below.", error_summary: false %> <!-- f: we don't need it to display task.errors -->
  <%= f.text_field :name %>
  <%= f.text_field :email %>
  <%= f.text_field :title %>
  <%= f.text_field :role %>
  <%= f.file_field :avatar, label: "Profile Image" %>

  <% if @user.has_password? %>
    <% if @user.persisted?%>
      <%= f.password_field :password_challenge, label: "Current Password"%>
    <% end %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation, label: "Confirm Password" %>
  <% end %>
  <%= f.primary @user.persisted? ? 'Update' : 'Sign Up' %>
<% end %>

app/views/users/_user.html.erb
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="<%= user.avatar.attached? ? url_for(user.avatar) : '#' %>" class="img-fluid rounded-start" alt="User image">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @user.name %></h5>
        <p class="card-text">Title: <%= @user.title%></p>
        <p class="card-text"><small class="text-body-secondary email"><%= @user.role%></small></p>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% title "Edit Info" %>
<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign Up" %>
<%= render 'form'%>

app/views/users/show.html.erb
<div id="user" class = "recipe-row"> 
  <div class = "recipe-col"> 
      <%= render @user%>
       <div class="dropdown">
         
          <% if current_user == @user %>
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Options
            </button> |
          <% end %>
          

          <%= link_to "All Recipes", recipes_path %>
        
          <ul class="dropdown-menu">
             <li><%= link_to "Edit Info", edit_user_path, class: "dropdown-item" %> </li>
            <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Delete</a></li>
          </ul>
       </div>
  </div>
</div>
<div id = "user_recipes" class = "recipe-row m-2">
   <div class = "recipe-col mx-2 align-self-start">
         <p class="d-inline-flex gap-1">
      <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Contributions
      </a>
    </p>
    <div class="collapse" id="collapseExample">
        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Recipe name</th>
            </tr>
          </thead>
           <tbody>
            <% @user.recipes.each do |r| %>
              <tr>
                <th scope="row"><%= r.id%></th>
                <td><%=r.name%></td>
              </tr>
            <% end %>
           </tbody>
      </table>


    </div>
  </div>
  
  <div id = "user_comments" class = "recipe-col mx-2 align-self-start">
    <p class="d-inline-flex gap-1">
      <a data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample1">
        Ratings
      </a>
    </p>
    <div class="collapse" id="collapseExample1">

        <% @user.comments.each do |r| %>
          <div class="card card-body">
            <p><%= link_to r.recipe.name, r.recipe%></p>
            <p>Message: <%= r.content%></p>
            <p>Rating: <%= r.rating%></p>
          </div>
        <% end %>

    </div>

  </div>
</div>
 


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Warning</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure to delete this user?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to 'Yes', @user, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>